// Este archivo centraliza los datos de las propiedades para toda la aplicación.
// Incluye 30 propiedades con imágenes de alta calidad y descripciones detalladas.

export const mockDataES = [
  // --- Primeras 9 propiedades con imágenes mejoradas ---
  {
    id: 1,
    title: "Villa de Lujo Frente al Mar en Bocagrande",
    type: "sale",
    price: 2800000000,
    location: "Bocagrande, Cartagena",
    bedrooms: 5,
    bathrooms: 6,
    sqft: 450,
    image: "https://images.pexels.com/photos/3288102/pexels-photo-3288102.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Espectacular villa moderna con acceso directo a la playa, piscina infinita y acabados de lujo.",
    features: ["Playa Privada", "Piscina Infinita", "Gimnasio", "Seguridad 24h", "Terraza con Vista al Mar"],
    agent: "Laura Gómez",
    phone: "+57 300 123 4567"
  },
  {
    id: 2,
    title: "Apartamento Colonial en la Ciudad Amurallada",
    type: "rental",
    pricePerNight: 550000,
    location: "Ciudad Amurallada, Cartagena",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 120,
    image: "https://images.pexels.com/photos/6585756/pexels-photo-6585756.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Elegante apartamento restaurado en el corazón del centro histórico. Combina el encanto colonial con el confort moderno.",
    features: ["Balcón Colonial", "AC Central", "WiFi de Alta Velocidad", "Cocina Equipada"],
    agent: "Carlos Rivas",
    phone: "+57 301 234 5678"
  },
  {
    id: 3,
    title: "Penthouse Moderno con Terraza 360°",
    type: "sale",
    price: 3500000000,
    location: "Bocagrande, Cartagena",
    bedrooms: 4,
    bathrooms: 5,
    sqft: 380,
    image: "https://images.pexels.com/photos/5998120/pexels-photo-5998120.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Exclusivo penthouse con terraza panorámica y vista 360° al mar Caribe y la ciudad amurallada.",
    features: ["Terraza 360°", "Jacuzzi Privado", "Ascensor Privado", "Acabados de Lujo"],
    agent: "Sofía Pérez",
    phone: "+57 302 345 6789"
  },
  {
    id: 4,
    title: "Casa Bohemía en Getsemaní",
    type: "rental",
    pricePerNight: 480000,
    location: "Getsemaní, Cartagena",
    bedrooms: 3,
    bathrooms: 3,
    sqft: 200,
    image: "https://images.pexels.com/photos/1879061/pexels-photo-1879061.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Auténtica casa colonial con patio central y piscina. Sumérgete en la cultura vibrante del barrio más bohemio.",
    features: ["Patio Central", "Arte Local", "Cocina Gourmet", "Piscina Privada"],
    agent: "Andrés Jaramillo",
    phone: "+57 303 456 7890"
  },
  {
    id: 5,
    title: "Apartamento Familiar en Manga",
    type: "sale",
    price: 1200000000,
    location: "Manga, Cartagena",
    bedrooms: 3,
    bathrooms: 3,
    sqft: 180,
    image: "https://images.pexels.com/photos/6492397/pexels-photo-6492397.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Moderno apartamento en conjunto residencial con amenidades completas. Ideal para familias que buscan tranquilidad.",
    features: ["Piscina", "Zona BBQ", "Seguridad 24h", "Gimnasio"],
    agent: "María Fernández",
    phone: "+57 304 567 8901"
  },
  {
    id: 6,
    title: "Loft Industrial Chic",
    type: "rental",
    pricePerNight: 320000,
    location: "Centro, Cartagena",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 85,
    image: "https://images.pexels.com/photos/6283835/pexels-photo-6283835.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Creativo loft con diseño industrial en el corazón de la ciudad. Un espacio único para viajeros y nómadas digitales.",
    features: ["Diseño Único", "Luz Natural", "Zona de Trabajo", "Cerca de Transporte"],
    agent: "Diego Martínez",
    phone: "+57 305 678 9012"
  },
  {
    id: 7,
    title: "Casa Republicana en San Diego",
    type: "sale",
    price: 1800000000,
    location: "San Diego, Cartagena",
    bedrooms: 4,
    bathrooms: 4,
    sqft: 320,
    image: "https://images.pexels.com/photos/6775268/pexels-photo-6775268.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Elegante casa republicana restaurada con detalles arquitectónicos originales y un patio de ensueño.",
    features: ["Arquitectura Original", "Patio Colonial", "Parking", "Terraza Superior"],
    agent: "Isabella Torres",
    phone: "+57 310 789 0123"
  },
  {
    id: 8,
    title: "Estudio con Vista al Mar en Castillogrande",
    type: "rental",
    pricePerNight: 380000,
    location: "Castillogrande, Cartagena",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 65,
    image: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Acogedor estudio con balcón y vista al mar en la exclusiva zona de Castillogrande. Ideal para parejas.",
    features: ["Vista al Mar", "Kitchenette", "Balcón", "Acceso a Playa"],
    agent: "Camila Rodríguez",
    phone: "+57 311 890 1234"
  },
  {
    id: 9,
    title: "Villa Familiar en El Laguito",
    type: "sale",
    price: 2200000000,
    location: "El Laguito, Cartagena",
    bedrooms: 4,
    bathrooms: 4,
    sqft: 350,
    image: "https://images.pexels.com/photos/2988860/pexels-photo-2988860.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Espaciosa villa familiar con jardín privado y acceso directo a la laguna. El lugar perfecto para crear recuerdos.",
    features: ["Jardín Privado", "Acceso a Laguna", "Zona de Niños", "Piscina"],
    agent: "Roberto Vargas",
    phone: "+57 312 901 2345"
  },
  // --- Nuevas propiedades (10-30) ---
  {
    id: 10,
    title: "Isla Privada en las Islas del Rosario",
    type: "rental",
    pricePerNight: 3500000,
    location: "Islas del Rosario, Cartagena",
    bedrooms: 6,
    bathrooms: 7,
    sqft: 800,
    image: "https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Experimenta el máximo lujo en tu propia isla privada. Con staff completo, muelle privado y aguas cristalinas.",
    features: ["Isla Privada", "Staff Completo", "Muelle Privado", "Snorkel", "Kayaks"],
    agent: "Elite Properties",
    phone: "+57 320 111 2233"
  },
  {
    id: 11,
    title: "Apartamento de Lujo en Morros",
    type: "sale",
    price: 1600000000,
    location: "Morros, Cartagena",
    bedrooms: 3,
    bathrooms: 4,
    sqft: 210,
    image: "https://images.pexels.com/photos/3935320/pexels-photo-3935320.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Vive frente a una de las mejores playas de Cartagena, con salida directa al mar y 5 piscinas.",
    features: ["Salida Directa al Mar", "5 Piscinas", "Gimnasio Moderno", "Restaurante Interno"],
    agent: "Sofía Pérez",
    phone: "+57 302 345 6789"
  },
  {
    id: 12,
    title: "Casa Histórica Restaurada en San Diego",
    type: "rental",
    pricePerNight: 950000,
    location: "San Diego, Cartagena",
    bedrooms: 5,
    bathrooms: 5,
    sqft: 400,
    image: "https://images.pexels.com/photos/4219175/pexels-photo-4219175.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Una joya arquitectónica con piscina en el patio central. Perfecta para grupos grandes que buscan exclusividad.",
    features: ["Piscina Central", "Rooftop con Jacuzzi", "Chef Privado (Opcional)", "Historia y Lujo"],
    agent: "Carlos Rivas",
    phone: "+57 301 234 5678"
  },
  {
    id: 13,
    title: "Villa Moderna en Manzanillo del Mar",
    type: "sale",
    price: 4100000000,
    location: "Manzanillo del Mar, Cartagena",
    bedrooms: 6,
    bathrooms: 8,
    sqft: 700,
    image: "https://images.pexels.com/photos/210617/pexels-photo-210617.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Diseño de vanguardia en un entorno tranquilo y exclusivo. Esta villa ofrece privacidad y espacios abiertos.",
    features: ["Campo de Golf Cercano", "Piscina Olímpica", "Cine en Casa", "Privacidad Total"],
    agent: "Laura Gómez",
    phone: "+57 300 123 4567"
  },
  {
    id: 14,
    title: "Atico Dúplex con Vistas al Puerto",
    type: "rental",
    pricePerNight: 650000,
    location: "Manga, Cartagena",
    bedrooms: 3,
    bathrooms: 3,
    sqft: 220,
    image: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Disfruta de vistas espectaculares al puerto de yates desde este ático dúplex con terraza y BBQ.",
    features: ["Vista al Puerto", "Terraza BBQ", "Diseño Dúplex", "Edificio Moderno"],
    agent: "Andrés Jaramillo",
    phone: "+57 303 456 7890"
  },
  {
    id: 15,
    title: "Apartamento Minimalista en Castillogrande",
    type: "sale",
    price: 980000000,
    location: "Castillogrande, Cartagena",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 130,
    image: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Elegancia y simplicidad con acabados de alta gama y una vista lateral a la bahía.",
    features: ["Diseño Minimalista", "Acabados de Lujo", "Pisos de Mármol", "Edificio Exclusivo"],
    agent: "María Fernández",
    phone: "+57 304 567 8901"
  },
  {
    id: 16,
    title: "Refugio Romántico en Getsemaní",
    type: "rental",
    pricePerNight: 420000,
    location: "Getsemaní, Cartagena",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 70,
    image: "https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Un pequeño oasis de paz con jacuzzi privado en la terraza, escondido en una callejuela colorida.",
    features: ["Jacuzzi en Terraza", "Diseño Bohemio", "Mucha Privacidad", "Cama King"],
    agent: "Diego Martínez",
    phone: "+57 305 678 9012"
  },
  {
    id: 17,
    title: "Casa de Lujo en la Ciudad Amurallada",
    type: "sale",
    price: 9000000000,
    location: "Ciudad Amurallada, Cartagena",
    bedrooms: 7,
    bathrooms: 9,
    sqft: 950,
    image: "https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Una de las propiedades más icónicas de Cartagena. Totalmente restaurada, con 2 piscinas y un rooftop de cine.",
    features: ["Propiedad Icónica", "2 Piscinas", "Rooftop Bar", "Cava de Vinos", "Gimnasio"],
    agent: "Elite Properties",
    phone: "+57 320 111 2233"
  },
  {
    id: 18,
    title: "Apartamento con Piscina Privada",
    type: "rental",
    pricePerNight: 800000,
    location: "Bocagrande, Cartagena",
    bedrooms: 3,
    bathrooms: 4,
    sqft: 250,
    image: "https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Un apartamento único con una pequeña piscina privada en su amplio balcón con vista al mar.",
    features: ["Piscina en Balcón", "Vista al Mar", "Amplio Balcón", "Edificio de Lujo"],
    agent: "Isabella Torres",
    phone: "+57 310 789 0123"
  },
  {
    id: 19,
    title: "Finca de Recreo en Tierra Bomba",
    type: "sale",
    price: 3200000000,
    location: "Tierra Bomba, Cartagena",
    bedrooms: 5,
    bathrooms: 5,
    sqft: 1200,
    image: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Escápate de la ciudad a esta finca con playa privada, kiosko y amplias zonas verdes a solo 10 minutos en bote.",
    features: ["Playa Privada", "Kiosko BBQ", "Muelle Propio", "Zonas Verdes"],
    agent: "Roberto Vargas",
    phone: "+57 312 901 2345"
  },
  {
    id: 20,
    title: "Loft en el Corazón de San Diego",
    type: "rental",
    pricePerNight: 400000,
    location: "San Diego, Cartagena",
    bedrooms: 1,
    bathrooms: 2,
    sqft: 90,
    image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Diseño contemporáneo en un edificio histórico. Perfecto para explorar la magia del centro a pie.",
    features: ["Ubicación Premium", "Diseño Moderno", "Cocina Abierta", "Balcón"],
    agent: "Camila Rodríguez",
    phone: "+57 311 890 1234"
  },
  {
    id: 21,
    title: "Apartamento Familiar en Morros",
    type: "sale",
    price: 1350000000,
    location: "Morros, Cartagena",
    bedrooms: 4,
    bathrooms: 4,
    sqft: 190,
    image: "https://images.pexels.com/photos/5998051/pexels-photo-5998051.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Amplitud y comodidad para toda la familia, con acceso directo a la playa y zonas sociales para niños.",
    features: ["Familiar", "Acceso a Playa", "Club de Playa", "Seguridad"],
    agent: "Laura Gómez",
    phone: "+57 300 123 4567"
  },
  {
    id: 22,
    title: "Cabaña de Lujo en Barú",
    type: "rental",
    pricePerNight: 1200000,
    location: "Barú, Cartagena",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 150,
    image: "https://images.pexels.com/photos/3624533/pexels-photo-3624533.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Desconéctate en esta cabaña de lujo sobre el agua, con acceso a playas de arena blanca y aguas turquesas.",
    features: ["Sobre el Agua", "Playas de Arena Blanca", "Privacidad", "Eco-Lodge"],
    agent: "Elite Properties",
    phone: "+57 320 111 2233"
  },
  {
    id: 23,
    title: "Penthouse con Piscina en Bocagrande",
    type: "sale",
    price: 2950000000,
    location: "Bocagrande, Cartagena",
    bedrooms: 3,
    bathrooms: 4,
    sqft: 330,
    image: "https://images.pexels.com/photos/3288103/pexels-photo-3288103.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Impresionante penthouse con piscina privada en la terraza y vistas panorámicas que te dejarán sin aliento.",
    features: ["Piscina Privada", "Vistas Panorámicas", "Terraza Doble Altura", "Domótica"],
    agent: "Sofía Pérez",
    phone: "+57 302 345 6789"
  },
  {
    id: 24,
    title: "Apartaestudio Moderno en La Matuna",
    type: "rental",
    pricePerNight: 250000,
    location: "La Matuna, Cartagena",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 50,
    image: "https://images.pexels.com/photos/275484/pexels-photo-275484.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Funcional y con estilo. Ideal para viajeros de negocios o estancias cortas en el distrito financiero.",
    features: ["Corporativo", "Excelente Ubicación", "Gimnasio", "Co-working en Edificio"],
    agent: "Carlos Rivas",
    phone: "+57 301 234 5678"
  },
  {
    id: 25,
    title: "Casa Republicana para Inversión",
    type: "sale",
    price: 1500000000,
    location: "Getsemaní, Cartagena",
    bedrooms: 8,
    bathrooms: 8,
    sqft: 500,
    image: "https://images.pexels.com/photos/6585764/pexels-photo-6585764.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Oportunidad de inversión. Casa para remodelar con gran potencial para hotel boutique o alquiler vacacional.",
    features: ["Potencial de Inversión", "Ubicación Estratégica", "Requiere Remodelación", "Alta Rentabilidad"],
    agent: "Andrés Jaramillo",
    phone: "+57 303 456 7890"
  },
  {
    id: 26,
    title: "Villa de Playa en las Islas",
    type: "rental",
    pricePerNight: 1800000,
    location: "Islas del Rosario, Cartagena",
    bedrooms: 4,
    bathrooms: 4,
    sqft: 300,
    image: "https://images.pexels.com/photos/1032591/pexels-photo-1032591.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Una villa caribeña clásica con muelle propio, rodeada de palmeras y con el mar a tus pies.",
    features: ["Estilo Caribeño", "Muelle", "Playa Semi-Privada", "Paz y Tranquilidad"],
    agent: "Isabella Torres",
    phone: "+57 310 789 0123"
  },
  {
    id: 27,
    title: "Apartamento con Balcón Grande",
    type: "sale",
    price: 890000000,
    location: "Crespo, Cartagena",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 140,
    image: "https://images.pexels.com/photos/2251247/pexels-photo-2251247.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Cerca al aeropuerto, este apartamento cuenta con un balcón excepcional para disfrutar de la brisa.",
    features: ["Balcón Grande", "Cerca al Aeropuerto", "Brillante y Fresco", "Unidad Familiar"],
    agent: "María Fernández",
    phone: "+57 304 567 8901"
  },
  {
    id: 28,
    title: "Suite de Lujo en Hotel Histórico",
    type: "rental",
    pricePerNight: 750000,
    location: "Ciudad Amurallada, Cartagena",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 80,
    image: "https://images.pexels.com/photos/262048/pexels-photo-262048.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Vive la experiencia de un hotel de 5 estrellas con la privacidad de una suite. Acceso a todas las amenidades.",
    features: ["Servicio de Hotel", "Piscina Histórica", "Restaurantes de Lujo", "Spa"],
    agent: "Diego Martínez",
    phone: "+57 305 678 9012"
  },
  {
    id: 29,
    title: "Casa Familiar con Jardín en Manga",
    type: "sale",
    price: 1950000000,
    location: "Manga, Cartagena",
    bedrooms: 4,
    bathrooms: 5,
    sqft: 400,
    image: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Una casa amplia con un gran jardín, ideal para una familia grande que valora el espacio y la tranquilidad.",
    features: ["Jardín Amplio", "Tranquilidad", "Espacios Generosos", "Potencial de Remodelación"],
    agent: "Roberto Vargas",
    phone: "+57 312 901 2345"
  },
  {
    id: 30,
    title: "Penthouse Minimalista en Morros",
    type: "rental",
    pricePerNight: 1100000,
    location: "Morros, Cartagena",
    bedrooms: 2,
    bathrooms: 3,
    sqft: 200,
    image: "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Lujo minimalista con una terraza privada y vistas directas al océano. Ideal para una escapada sofisticada.",
    features: ["Diseño de Autor", "Terraza Privada", "Vistas al Océano", "Acceso a Playa"],
    agent: "Camila Rodríguez",
    phone: "+57 311 890 1234"
  }
];

export const mockDataEN = [
  // --- First 9 properties with enhanced images ---
  {
    id: 1,
    title: "Luxury Oceanfront Villa in Bocagrande",
    type: "sale",
    price: 3800000000, // Converted from 950000 USD * 4000 COP/USD
    location: "Bocagrande, Cartagena",
    bedrooms: 5,
    bathrooms: 6,
    sqft: 4850,
    image: "https://images.pexels.com/photos/3288102/pexels-photo-3288102.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Spectacular modern villa with direct beach access, an infinity pool, and luxury finishes.",
    features: ["Private Beach", "Infinity Pool", "Gym", "24h Security", "Ocean View Terrace"],
    agent: "Laura Gómez",
    phone: "+57 300 123 4567"
  },
  {
    id: 2,
    title: "Colonial Apartment in the Walled City",
    type: "rental",
    pricePerNight: 720000, // Converted from 180 USD * 4000 COP/USD
    location: "Walled City, Cartagena",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1300,
    image: "https://images.pexels.com/photos/6585756/pexels-photo-6585756.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Elegant restored apartment in the heart of the historic center. It combines colonial charm with modern comfort.",
    features: ["Colonial Balcony", "Central AC", "High-Speed WiFi", "Equipped Kitchen"],
    agent: "Carlos Rivas",
    phone: "+57 301 234 5678"
  },
  {
    id: 3,
    title: "Modern Penthouse with 360° Terrace",
    type: "sale",
    price: 4800000000, // Converted from 1200000 USD * 4000 COP/USD
    location: "Bocagrande, Cartagena",
    bedrooms: 4,
    bathrooms: 5,
    sqft: 4100,
    image: "https://images.pexels.com/photos/5998120/pexels-photo-5998120.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Exclusive penthouse with a panoramic terrace and 360° views of the Caribbean Sea and the walled city.",
    features: ["360° Terrace", "Private Jacuzzi", "Private Elevator", "Luxury Finishes"],
    agent: "Sofía Pérez",
    phone: "+57 302 345 6789"
  },
  {
    id: 4,
    title: "Bohemian House in Getsemaní",
    type: "rental",
    pricePerNight: 640000, // Converted from 160 USD * 4000 COP/USD
    location: "Getsemaní, Cartagena",
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2150,
    image: "https://images.pexels.com/photos/1879061/pexels-photo-1879061.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Authentic colonial house with a central courtyard and pool. Immerse yourself in the vibrant culture of the most bohemian neighborhood.",
    features: ["Central Courtyard", "Local Art", "Gourmet Kitchen", "Private Pool"],
    agent: "Andrés Jaramillo",
    phone: "+57 303 456 7890"
  },
  {
    id: 5,
    title: "Family Apartment in Manga",
    type: "sale",
    price: 1600000000, // Converted from 400000 USD * 4000 COP/USD
    location: "Manga, Cartagena",
    bedrooms: 3,
    bathrooms: 3,
    sqft: 1940,
    image: "https://images.pexels.com/photos/6492397/pexels-photo-6492397.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Modern apartment in a residential complex with full amenities. Ideal for families seeking tranquility.",
    features: ["Pool", "BBQ Area", "24h Security", "Gym"],
    agent: "María Fernández",
    phone: "+57 304 567 8901"
  },
  {
    id: 6,
    title: "Industrial Chic Loft",
    type: "rental",
    pricePerNight: 360000, // Converted from 90 USD * 4000 COP/USD
    location: "Centro, Cartagena",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 915,
    image: "https://images.pexels.com/photos/6283835/pexels-photo-6283835.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Creative loft with an industrial design in the heart of the city. A unique space for travelers and digital nomads.",
    features: ["Unique Design", "Natural Light", "Workspace", "Near Transportation"],
    agent: "Diego Martínez",
    phone: "+57 305 678 9012"
  },
  {
    id: 7,
    title: "Republican House in San Diego",
    type: "sale",
    price: 2400000000, // Converted from 600000 USD * 4000 COP/USD
    location: "San Diego, Cartagena",
    bedrooms: 4,
    bathrooms: 4,
    sqft: 3445,
    image: "https://images.pexels.com/photos/6775268/pexels-photo-6775268.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Elegant restored republican house with original architectural details and a dreamlike courtyard.",
    features: ["Original Architecture", "Colonial Courtyard", "Parking", "Rooftop Terrace"],
    agent: "Isabella Torres",
    phone: "+57 310 789 0123"
  },
  {
    id: 8,
    title: "Studio with Ocean View in Castillogrande",
    type: "rental",
    pricePerNight: 500000, // Converted from 125 USD * 4000 COP/USD
    location: "Castillogrande, Cartagena",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 700,
    image: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Cozy studio with a balcony and ocean view in the exclusive Castillogrande area. Ideal for couples.",
    features: ["Ocean View", "Kitchenette", "Balcony", "Beach Access"],
    agent: "Camila Rodríguez",
    phone: "+57 311 890 1234"
  },
  {
    id: 9,
    title: "Family Villa in El Laguito",
    type: "sale",
    price: 2920000000, // Converted from 730000 USD * 4000 COP/USD
    location: "El Laguito, Cartagena",
    bedrooms: 4,
    bathrooms: 4,
    sqft: 3770,
    image: "https://images.pexels.com/photos/2988860/pexels-photo-2988860.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Spacious family villa with a private garden and direct access to the lagoon. The perfect place to create memories.",
    features: ["Private Garden", "Lagoon Access", "Kids Area", "Pool"],
    agent: "Roberto Vargas",
    phone: "+57 312 901 2345"
  },
  // --- New properties (10-30) ---
  {
    id: 10,
    title: "Private Island in the Rosario Islands",
    type: "rental",
    pricePerNight: 3800000, // Converted from 950 USD * 4000 COP/USD
    location: "Islas del Rosario, Cartagena",
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8600,
    image: "https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Experience ultimate luxury on your own private island. With a full staff, private dock, and crystal-clear waters.",
    features: ["Private Island", "Full Staff", "Private Dock", "Snorkeling", "Kayaks"],
    agent: "Elite Properties",
    phone: "+57 320 111 2233"
  },
  {
    id: 11,
    title: "Luxury Apartment in Morros",
    type: "sale",
    price: 2120000000, // Converted from 530000 USD * 4000 COP/USD
    location: "Morros, Cartagena",
    bedrooms: 3,
    bathrooms: 4,
    sqft: 2260,
    image: "https://images.pexels.com/photos/3935320/pexels-photo-3935320.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Live in front of one of the best beaches in Cartagena, with direct ocean access and 5 pools.",
    features: ["Direct Beach Access", "5 Pools", "Modern Gym", "Internal Restaurant"],
    agent: "Sofía Pérez",
    phone: "+57 302 345 6789"
  },
  {
    id: 12,
    title: "Restored Historic House in San Diego",
    type: "rental",
    pricePerNight: 1000000, // Converted from 250 USD * 4000 COP/USD
    location: "San Diego, Cartagena",
    bedrooms: 5,
    bathrooms: 5,
    sqft: 4300,
    image: "https://images.pexels.com/photos/4219175/pexels-photo-4219175.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "An architectural gem with a pool in the central courtyard. Perfect for large groups seeking exclusivity.",
    features: ["Central Pool", "Rooftop Jacuzzi", "Private Chef (Optional)", "History and Luxury"],
    agent: "Carlos Rivas",
    phone: "+57 301 234 5678"
  },
  {
    id: 13,
    title: "Modern Villa in Manzanillo del Mar",
    type: "sale",
    price: 5400000000, // Converted from 1350000 USD * 4000 COP/USD
    location: "Manzanillo del Mar, Cartagena",
    bedrooms: 6,
    bathrooms: 8,
    sqft: 7530,
    image: "https://images.pexels.com/photos/210617/pexels-photo-210617.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Avant-garde design in a quiet and exclusive environment. This villa offers privacy and open spaces.",
    features: ["Nearby Golf Course", "Olympic Pool", "Home Theater", "Total Privacy"],
    agent: "Laura Gómez",
    phone: "+57 300 123 4567"
  },
  {
    id: 14,
    title: "Duplex Penthouse with Harbor Views",
    type: "rental",
    pricePerNight: 700000, // Converted from 175 USD * 4000 COP/USD
    location: "Manga, Cartagena",
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2370,
    image: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Enjoy spectacular views of the yacht harbor from this duplex penthouse with a terrace and BBQ.",
    features: ["Harbor View", "BBQ Terrace", "Duplex Design", "Modern Building"],
    agent: "Andrés Jaramillo",
    phone: "+57 303 456 7890"
  },
  {
    id: 15,
    title: "Minimalist Apartment in Castillogrande",
    type: "sale",
    price: 1300000000, // Converted from 325000 USD * 4000 COP/USD
    location: "Castillogrande, Cartagena",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1400,
    image: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Elegance and simplicity with high-end finishes and a side view of the bay.",
    features: ["Minimalist Design", "Luxury Finishes", "Marble Floors", "Exclusive Building"],
    agent: "María Fernández",
    phone: "+57 304 567 8901"
  },
  {
    id: 16,
    title: "Romantic Getaway in Getsemaní",
    type: "rental",
    pricePerNight: 560000, // Converted from 140 USD * 4000 COP/USD
    location: "Getsemaní, Cartagena",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 750,
    image: "https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "A small oasis of peace with a private jacuzzi on the terrace, hidden in a colorful alley.",
    features: ["Rooftop Jacuzzi", "Bohemian Design", "High Privacy", "King Bed"],
    agent: "Diego Martínez",
    phone: "+57 305 678 9012"
  },
  {
    id: 17,
    title: "Luxury House in the Walled City",
    type: "sale",
    price: 12000000000, // Converted from 3000000 USD * 4000 COP/USD
    location: "Walled City, Cartagena",
    bedrooms: 7,
    bathrooms: 9,
    sqft: 10225,
    image: "https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "One of the most iconic properties in Cartagena. Fully restored, with 2 pools and a cinematic rooftop.",
    features: ["Iconic Property", "2 Pools", "Rooftop Bar", "Wine Cellar", "Gym"],
    agent: "Elite Properties",
    phone: "+57 320 111 2233"
  },
  {
    id: 18,
    title: "Apartment with Private Plunge Pool",
    type: "rental",
    pricePerNight: 840000, // Converted from 210 USD * 4000 COP/USD
    location: "Bocagrande, Cartagena",
    bedrooms: 3,
    bathrooms: 4,
    sqft: 2690,
    image: "https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "A unique apartment with a small private pool on its spacious balcony overlooking the sea.",
    features: ["Balcony Pool", "Ocean View", "Spacious Balcony", "Luxury Building"],
    agent: "Isabella Torres",
    phone: "+57 310 789 0123"
  },
  {
    id: 19,
    title: "Recreational Estate on Tierra Bomba",
    type: "sale",
    price: 4200000000, // Converted from 1050000 USD * 4000 COP/USD
    location: "Tierra Bomba, Cartagena",
    bedrooms: 5,
    bathrooms: 5,
    sqft: 12900,
    image: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Escape the city to this estate with a private beach, kiosk, and large green areas just a 10-minute boat ride away.",
    features: ["Private Beach", "BBQ Kiosk", "Own Dock", "Green Areas"],
    agent: "Roberto Vargas",
    phone: "+57 312 901 2345"
  },
  {
    id: 20,
    title: "Loft in the Heart of San Diego",
    type: "rental",
    pricePerNight: 520000, // Converted from 130 USD * 4000 COP/USD
    location: "San Diego, Cartagena",
    bedrooms: 1,
    bathrooms: 2,
    sqft: 970,
    image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Contemporary design in a historic building. Perfect for exploring the magic of the center on foot.",
    features: ["Premium Location", "Modern Design", "Open Kitchen", "Balcony"],
    agent: "Camila Rodríguez",
    phone: "+57 311 890 1234"
  },
  {
    id: 21,
    title: "Family Apartment in Morros",
    type: "sale",
    price: 1800000000, // Converted from 450000 USD * 4000 COP/USD
    location: "Morros, Cartagena",
    bedrooms: 4,
    bathrooms: 4,
    sqft: 2045,
    image: "https://images.pexels.com/photos/5998051/pexels-photo-5998051.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Spaciousness and comfort for the whole family, with direct beach access and social areas for children.",
    features: ["Family-Friendly", "Beach Access", "Beach Club", "Security"],
    agent: "Laura Gómez",
    phone: "+57 300 123 4567"
  },
  {
    id: 22,
    title: "Luxury Cabin in Barú",
    type: "rental",
    pricePerNight: 1280000, // Converted from 320 USD * 4000 COP/USD
    location: "Barú, Cartagena",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1615,
    image: "https://images.pexels.com/photos/3624533/pexels-photo-3624533.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Disconnect in this luxury overwater cabin, with access to white sandy beaches and turquoise waters.",
    features: ["Overwater", "White Sand Beaches", "Privacy", "Eco-Lodge"],
    agent: "Elite Properties",
    phone: "+57 320 111 2233"
  },
  {
    id: 23,
    title: "Penthouse with Rooftop Pool in Bocagrande",
    type: "sale",
    price: 3920000000, // Converted from 980000 USD * 4000 COP/USD
    location: "Bocagrande, Cartagena",
    bedrooms: 3,
    bathrooms: 4,
    sqft: 3550,
    image: "https://images.pexels.com/photos/3288103/pexels-photo-3288103.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Stunning penthouse with a private pool on the terrace and breathtaking panoramic views.",
    features: ["Private Pool", "Panoramic Views", "Double-Height Terrace", "Home Automation"],
    agent: "Sofía Pérez",
    phone: "+57 302 345 6789"
  },
  {
    id: 24,
    title: "Modern Studio in La Matuna",
    type: "rental",
    pricePerNight: 280000, // Converted from 70 USD * 4000 COP/USD
    location: "La Matuna, Cartagena",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 540,
    image: "https://images.pexels.com/photos/275484/pexels-photo-275484.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Functional and stylish. Ideal for business travelers or short stays in the financial district.",
    features: ["Corporate-Friendly", "Excellent Location", "Gym", "In-Building Co-working"],
    agent: "Carlos Rivas",
    phone: "+57 301 234 5678"
  },
  {
    id: 25,
    title: "Republican House for Investment",
    type: "sale",
    price: 2000000000, // Converted from 500000 USD * 4000 COP/USD
    location: "Getsemaní, Cartagena",
    bedrooms: 8,
    bathrooms: 8,
    sqft: 5380,
    image: "https://images.pexels.com/photos/6585764/pexels-photo-6585764.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Investment opportunity. House to remodel with great potential for a boutique hotel or vacation rental.",
    features: ["Investment Potential", "Strategic Location", "Needs Remodeling", "High Profitability"],
    agent: "Andrés Jaramillo",
    phone: "+57 303 456 7890"
  },
  {
    id: 26,
    title: "Beach Villa in the Islands",
    type: "rental",
    pricePerNight: 1920000, // Converted from 480 USD * 4000 COP/USD
    location: "Islas del Rosario, Cartagena",
    bedrooms: 4,
    bathrooms: 4,
    sqft: 3230,
    image: "https://images.pexels.com/photos/1032591/pexels-photo-1032591.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "A classic Caribbean villa with its own dock, surrounded by palm trees and with the sea at your feet.",
    features: ["Caribbean Style", "Dock", "Semi-Private Beach", "Peace and Quiet"],
    agent: "Isabella Torres",
    phone: "+57 310 789 0123"
  },
  {
    id: 27,
    title: "Apartment with a Large Balcony",
    type: "sale",
    price: 1180000000, // Converted from 295000 USD * 4000 COP/USD
    location: "Crespo, Cartagena",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1500,
    image: "https://images.pexels.com/photos/2251247/pexels-photo-2251247.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Near the airport, this apartment features an exceptional balcony to enjoy the breeze.",
    features: ["Large Balcony", "Near the Airport", "Bright and Fresh", "Family Unit"],
    agent: "María Fernández",
    phone: "+57 304 567 8901"
  },
  {
    id: 28,
    title: "Luxury Suite in a Historic Hotel",
    type: "rental",
    pricePerNight: 800000, // Converted from 200 USD * 4000 COP/USD
    location: "Walled City, Cartagena",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 860,
    image: "https://images.pexels.com/photos/262048/pexels-photo-262048.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Live the 5-star hotel experience with the privacy of a suite. Access to all amenities.",
    features: ["Hotel Service", "Historic Pool", "Luxury Restaurants", "Spa"],
    agent: "Diego Martínez",
    phone: "+57 305 678 9012"
  },
  {
    id: 29,
    title: "Family House with Garden in Manga",
    type: "sale",
    price: 2600000000, // Converted from 650000 USD * 4000 COP/USD
    location: "Manga, Cartagena",
    bedrooms: 4,
    bathrooms: 5,
    sqft: 4300,
    image: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "A spacious house with a large garden, ideal for a large family that values space and tranquility.",
    features: ["Large Garden", "Tranquility", "Generous Spaces", "Remodeling Potential"],
    agent: "Roberto Vargas",
    phone: "+57 312 901 2345"
  },
  {
    id: 30,
    title: "Minimalist Penthouse in Morros",
    type: "rental",
    pricePerNight: 1160000, // Converted from 290 USD * 4000 COP/USD
    location: "Morros, Cartagena",
    bedrooms: 2,
    bathrooms: 3,
    sqft: 2150,
    image: "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description: "Minimalist luxury with a private terrace and direct ocean views. Ideal for a sophisticated getaway.",
    features: ["Designer Finishes", "Private Terrace", "Ocean Views", "Beach Access"],
    agent: "Camila Rodríguez",
    phone: "+57 311 890 1234"
  }
];